services:
    web:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - "48080:80"
        volumes:
            - ./html:/html
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
          - internal
    php:
        image: php:fpm-alpine
        restart: unless-stopped
        volumes:
            - ./html:/html
            - ./src/private:/private
        networks:
          - internal
    governor:
        image: aquova/governor:latest
        restart: unless-stopped
        volumes:
            - ./private:/governor/private
networks:
  internal:
    driver: bridge
