version: '3'
services:
    web:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./html:/html
            - ./site.conf:/etc/nginx/conf.d/default.conf
    php:
        image: php:7.3-fpm
        volumes:
            - ./html:/html
            - ./private:/private
    governor:
        image: aquova/governor:latest
        restart: unless-stopped
        volumes:
            - ./src:/governor
            - ./private:/private
