services:
    web:
        image: dunglas/frankenphp:latest
        restart: unless-stopped
        ports:
            - 8080:8080
        volumes:
            - ./html:/app/public
            - ./private:/private
        environment:
            - SERVER_NAME=:8080
    governor:
        image: aquova/governor:latest
        restart: unless-stopped
        volumes:
            - ./private:/governor/private
